import type {
  FilingsProviderName,
  LlmProviderName,
  MetricsProviderName,
  NewsProviderName,
  NewsRelevanceModeName,
  NewsV2SourceQualityModeName,
} from "./options";

type DefaultConfig = {
  APP_SYMBOLS: string;
  APP_RESEARCH_INTERVAL_SECONDS: number;
  API_PORT: number;
  APP_NEWS_LOOKBACK_DAYS: number;
  APP_FILINGS_LOOKBACK_DAYS: number;
  NEWS_PROVIDER: NewsProviderName;
  NEWS_PROVIDERS: string;
  FINNHUB_BASE_URL: string;
  FINNHUB_TIMEOUT_MS: number;
  FINNHUB_MIN_INTERVAL_MS: number;
  ALPHA_VANTAGE_BASE_URL: string;
  ALPHA_VANTAGE_TIMEOUT_MS: number;
  ALPHA_VANTAGE_MIN_INTERVAL_MS: number;
  METRICS_PROVIDER: MetricsProviderName;
  FILINGS_PROVIDER: FilingsProviderName;
  SEC_EDGAR_BASE_URL: string;
  SEC_EDGAR_ARCHIVES_BASE_URL: string;
  SEC_EDGAR_TICKERS_URL: string;
  SEC_EDGAR_TIMEOUT_MS: number;
  SEC_EDGAR_MIN_INTERVAL_MS: number;
  SEC_COMPANYFACTS_ENABLED: boolean;
  SEC_COMPANYFACTS_TIMEOUT_MS: number;
  SEC_COMPANYFACTS_MAX_FACTS_PER_METRIC: number;
  MACRO_OVERLAY_ENABLED: boolean;
  MACRO_FRED_ENABLED: boolean;
  MACRO_BLS_ENABLED: boolean;
  MACRO_LOOKBACK_MONTHS: number;
  FRED_BASE_URL: string;
  FRED_TIMEOUT_MS: number;
  FRED_MIN_INTERVAL_MS: number;
  BLS_BASE_URL: string;
  BLS_TIMEOUT_MS: number;
  BLS_MIN_INTERVAL_MS: number;
  LLM_PROVIDER: LlmProviderName;
  OLLAMA_BASE_URL: string;
  OLLAMA_CHAT_MODEL: string;
  OLLAMA_EMBED_MODEL: string;
  OLLAMA_CHAT_TIMEOUT_MS: number;
  OLLAMA_EMBED_TIMEOUT_MS: number;
  OPENAI_BASE_URL: string;
  OPENAI_CHAT_MODEL: string;
  OPENAI_CHAT_TIMEOUT_MS: number;
  NEWS_RELEVANCE_MODE: NewsRelevanceModeName;
  NEWS_MIN_RELEVANCE_SCORE: number;
  NEWS_ISSUER_MATCH_MIN_FIELDS: number;
  THESIS_TRIGGER_MIN_NUMERIC: number;
  THESIS_GENERIC_PHRASE_MAX: number;
  THESIS_MIN_CITATION_COVERAGE_PCT: number;
  THESIS_QUALITY_MIN_SCORE: number;
  THESIS_KPI_CARRY_FORWARD_MAX_AGE_DAYS: number;
  THESIS_CORE_KPI_MIN_REQUIRED: number;
  THESIS_GRACE_ALLOW_ON_SECTOR_WEAKNESS: boolean;
  NEWS_V2_MIN_COMPOSITE_SCORE: number;
  NEWS_V2_MIN_MATERIALITY_SCORE: number;
  NEWS_V2_MIN_KPI_LINKAGE_SCORE: number;
  NEWS_V2_MAX_ITEMS: number;
  NEWS_V2_SOURCE_QUALITY_MODE: NewsV2SourceQualityModeName;
  ALPHA_VANTAGE_DAILY_REQUEST_CAP: number;
  QUEUE_CONCURRENCY_INGEST: number;
  QUEUE_CONCURRENCY_NORMALIZE: number;
  QUEUE_CONCURRENCY_CLASSIFY_STOCK: number;
  QUEUE_CONCURRENCY_SELECT_HORIZON: number;
  QUEUE_CONCURRENCY_BUILD_KPI_TREE: number;
  QUEUE_CONCURRENCY_EMBED: number;
  QUEUE_CONCURRENCY_SYNTHESIZE: number;
};

/**
 * Central default values for non-sensitive runtime configuration.
 * Keeping these in source control makes behavior explicit and reviewable.
 */
export const defaultConfig: DefaultConfig = {
  APP_SYMBOLS: "",
  APP_RESEARCH_INTERVAL_SECONDS: 300,
  API_PORT: 3000,
  APP_NEWS_LOOKBACK_DAYS: 7,
  APP_FILINGS_LOOKBACK_DAYS: 90,
  NEWS_PROVIDER: "finnhub",
  NEWS_PROVIDERS: "",
  FINNHUB_BASE_URL: "https://finnhub.io",
  FINNHUB_TIMEOUT_MS: 10_000,
  FINNHUB_MIN_INTERVAL_MS: 1_000,
  ALPHA_VANTAGE_BASE_URL: "https://www.alphavantage.co",
  ALPHA_VANTAGE_TIMEOUT_MS: 10_000,
  ALPHA_VANTAGE_MIN_INTERVAL_MS: 1_000,
  METRICS_PROVIDER: "alphavantage",
  FILINGS_PROVIDER: "sec-edgar",
  SEC_EDGAR_BASE_URL: "https://data.sec.gov",
  SEC_EDGAR_ARCHIVES_BASE_URL: "https://www.sec.gov/Archives/edgar/data",
  SEC_EDGAR_TICKERS_URL: "https://www.sec.gov/files/company_tickers.json",
  SEC_EDGAR_TIMEOUT_MS: 15_000,
  SEC_EDGAR_MIN_INTERVAL_MS: 1_000,
  SEC_COMPANYFACTS_ENABLED: true,
  SEC_COMPANYFACTS_TIMEOUT_MS: 15_000,
  SEC_COMPANYFACTS_MAX_FACTS_PER_METRIC: 16,
  MACRO_OVERLAY_ENABLED: true,
  MACRO_FRED_ENABLED: true,
  MACRO_BLS_ENABLED: true,
  MACRO_LOOKBACK_MONTHS: 24,
  FRED_BASE_URL: "https://api.stlouisfed.org",
  FRED_TIMEOUT_MS: 15_000,
  FRED_MIN_INTERVAL_MS: 1_000,
  BLS_BASE_URL: "https://api.bls.gov",
  BLS_TIMEOUT_MS: 15_000,
  BLS_MIN_INTERVAL_MS: 1_000,
  LLM_PROVIDER: "openai",
  OLLAMA_BASE_URL: "http://localhost:11434",
  OLLAMA_CHAT_MODEL: "qwen2.5:7b-instruct",
  OLLAMA_EMBED_MODEL: "mxbai-embed-large",
  OLLAMA_CHAT_TIMEOUT_MS: 180_000,
  OLLAMA_EMBED_TIMEOUT_MS: 30_000,
  OPENAI_BASE_URL: "https://api.openai.com",
  OPENAI_CHAT_MODEL: "gpt-4.1",
  OPENAI_CHAT_TIMEOUT_MS: 60_000,
  NEWS_RELEVANCE_MODE: "high_precision",
  NEWS_MIN_RELEVANCE_SCORE: 7,
  NEWS_ISSUER_MATCH_MIN_FIELDS: 1,
  THESIS_TRIGGER_MIN_NUMERIC: 3,
  THESIS_GENERIC_PHRASE_MAX: 0,
  THESIS_MIN_CITATION_COVERAGE_PCT: 80,
  THESIS_QUALITY_MIN_SCORE: 75,
  THESIS_KPI_CARRY_FORWARD_MAX_AGE_DAYS: 90,
  THESIS_CORE_KPI_MIN_REQUIRED: 2,
  THESIS_GRACE_ALLOW_ON_SECTOR_WEAKNESS: true,
  NEWS_V2_MIN_COMPOSITE_SCORE: 65,
  NEWS_V2_MIN_MATERIALITY_SCORE: 50,
  NEWS_V2_MIN_KPI_LINKAGE_SCORE: 40,
  NEWS_V2_MAX_ITEMS: 10,
  NEWS_V2_SOURCE_QUALITY_MODE: "default",
  ALPHA_VANTAGE_DAILY_REQUEST_CAP: 25,
  QUEUE_CONCURRENCY_INGEST: 2,
  QUEUE_CONCURRENCY_NORMALIZE: 2,
  QUEUE_CONCURRENCY_CLASSIFY_STOCK: 2,
  QUEUE_CONCURRENCY_SELECT_HORIZON: 2,
  QUEUE_CONCURRENCY_BUILD_KPI_TREE: 2,
  QUEUE_CONCURRENCY_EMBED: 2,
  QUEUE_CONCURRENCY_SYNTHESIZE: 1,
};
